steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - 'SESSION_MAXAGE=${_SESSION_MAXAGE}'
      - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
      - 'BUCKET_NAME=${_BUCKET_NAME}'
      - 'URL_EXPIRATION_TIME=${_URL_EXPIRATION_TIME}'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - 'CREDS_URL=${_CREDS_URL}'
      - 'GCR_SERVICE_NAME=${_GCR_SERVICE_NAME}'
  - name: gcr.io/cloud-builders/docker
    args: ["compose", "build"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO_NAME}"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_GCR_SERVICE_NAME}', '--image', 'gcr.io/${PROJECT_ID}/${LOCATION}-docker.pkg.dev/${PROJECT_ID}/{GAR_REPO_NAME}', '--region', 'SERVICE_REGION']
    
options:
  logging: CLOUD_LOGGING_ONLY