steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/gamma-pameran/github.com/reigenleif/gamma-pameran:$COMMIT_SHA", "-f", "Dockerfile", "."]
options:
  logging: CLOUD_LOGGING_ONLY