steps:
  - name: gcr.io/cloud-builders/docker
    args: ["compose", "build"]
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - 'SESSION_MAXAGE=${_SESSION_MAXAGE}'
      - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
      - 'BUCKET_NAME=${_BUCKET_NAME}'
      - 'URL_EXPIRATION_TIME=${_URL_EXPIRATION_TIME}'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - 'CREDS_URL=${_CREDS_URL}'
  - name: gcr.io/cloud-builders/docker
    args: ["push", "asia-southeast1-docker.pkg.dev/${PROJECT_ID}/terrakota-stock-exchange/terrakota-stock-exchange"]
    
options:
  logging: CLOUD_LOGGING_ONLY